### ISSUE TITLE
I own a Tuya/Smartlife thermostat (product_id: "9myqvomgygt9zgcs") that show similar problems in HA (tested with both this integration and the default HA Tuya integration).

### ISSUE THREAD

**Issue by andrus2049** [tuya/tuya-smart-life#34]
I own a Tuya/Smartlife thermostat (product_id: "9myqvomgygt9zgcs") that show similar problems in HA (tested with both this integration and the default HA Tuya integration).

Problems are mainly related to incorrect HVAC_MODEs (shown and settable), and Presets.
With the SmartLife Android app everything is fine.
Here I show the situation using the Smart Life (Beta) Home Assistant Integration.
Mode set on  IoT Tuya platform: **DP instruction**

Hope this help solving the compatibility issues with HA, thanks.

<img width="237" alt="thermostat" src="https://github.com/tuya/tuya-smart-life/assets/36678690/ad0b9940-88c4-4c05-a92e-33d235f0b116">

Here the sets from IoT Tuya platform:
---------------------------------------------------------------------
**STANDARD INSTRUCTION SET**

switch	Boolean	
"{true,false}"
mode	Enum	
{
  "range": [
    "auto",
    "holiday",
    "manual",
    "temporary"
  ]
}
temp_set	Integer	
{
  "unit": "℃",
  "min": 5,
  "max": 350,
  "scale": 1,
  "step": 1
}
upper_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
lower_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
temp_correction	Integer	
{
  "unit": "",
  "min": -30,
  "max": 30,
  "scale": 1,
  "step": 5
}
holiday_temp_set	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
holiday_days_set	Integer	
{
  "unit": "day",
  "min": 0,
  "max": 3000,
  "scale": 0,
  "step": 1
}
week_program2	Raw	
{}
factory_reset	Boolean	
"{true,false}"
child_lock	Boolean	
"{true,false}"
temporary_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 2880,
  "scale": 0,
  "step": 1
}
temp_antifreezing	Integer	
{
  "unit": "",
  "min": 5,
  "max": 150,
  "scale": 1,
  "step": 1
}
swing	Integer	
{
  "unit": "",
  "min": 2,
  "max": 20,
  "scale": 1,
  "step": 1
}
heatcool_heat_cool	Enum	
{
  "range": [
    "hc_heat",
    "hc_cool",
    "heat",
    "cool"
  ]
}
antifreezing_switch	Boolean	
"{true,false}"
use_password	Boolean	
"{true,false}"
password	Integer	
{
  "unit": "4",
  "min": 0,
  "max": 9999,
  "scale": 0,
  "step": 1
}
partial_key_lock	Boolean	
"{true,false}"

--------------------------------------------------------------
**STANDARD STATUS SET**

switch	Boolean	
"{true,false}"
mode	Enum	
{
  "range": [
    "auto",
    "holiday",
    "manual",
    "temporary"
  ]
}
work_state	Enum	
{
  "range": [
    "off",
    "heat",
    "cool"
  ]
}
temp_set	Integer	
{
  "unit": "℃",
  "min": 5,
  "max": 350,
  "scale": 1,
  "step": 1
}
upper_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
temp_current	Integer	
{
  "unit": "℃",
  "min": 0,
  "max": 400,
  "scale": 1,
  "step": 1
}
lower_temp	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
temp_correction	Integer	
{
  "unit": "",
  "min": -30,
  "max": 30,
  "scale": 1,
  "step": 5
}
holiday_temp_set	Integer	
{
  "unit": "℃",
  "min": 50,
  "max": 350,
  "scale": 1,
  "step": 1
}
holiday_days_set	Integer	
{
  "unit": "day",
  "min": 0,
  "max": 3000,
  "scale": 0,
  "step": 1
}
week_program2	Raw	
{}
factory_reset	Boolean	
"{true,false}"
child_lock	Boolean	
"{true,false}"
countdown_left	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 2880,
  "scale": 0,
  "step": 1
}
fault	Bitmap	
{
  "label": [
    "e1",
    "e2",
    "e3",
    "e4",
    "e5",
    "e6",
    "e7",
    "e8",
    "e9",
    "e10"
  ],
  "maxlen": 10
}
temporary_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 2880,
  "scale": 0,
  "step": 1
}
total_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 999999,
  "scale": 0,
  "step": 1
}
temp_antifreezing	Integer	
{
  "unit": "",
  "min": 5,
  "max": 150,
  "scale": 1,
  "step": 1
}
swing	Integer	
{
  "unit": "",
  "min": 2,
  "max": 20,
  "scale": 1,
  "step": 1
}
time_period	Integer	
{
  "unit": "",
  "min": 1,
  "max": 9,
  "scale": 0,
  "step": 1
}
electricity	Integer	
{
  "unit": "",
  "min": 0,
  "max": 6000,
  "scale": 0,
  "step": 1
}
curent_pro_time	Raw	
{}
heatcool_heat_cool	Enum	
{
  "range": [
    "hc_heat",
    "hc_cool",
    "heat",
    "cool"
  ]
}
antifreezing_switch	Boolean	
"{true,false}"
use_password	Boolean	
"{true,false}"
true_off	Boolean	
"{true,false}"
password	Integer	
{
  "unit": "4",
  "min": 0,
  "max": 9999,
  "scale": 0,
  "step": 1
}
partial_key_lock	Boolean	
"{true,false}"

----------------------------------------------------------------
**DEVICE QUERY PROPERTIES**

{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1700677459517,
        "value": true
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1700677373229,
        "value": "manual"
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 3,
        "time": 1700612410472,
        "value": "off"
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 16,
        "time": 1700678722885,
        "value": 214
      },
      {
        "code": "upper_temp",
        "custom_name": "",
        "dp_id": 19,
        "time": 1700073411555,
        "value": 240
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 24,
        "time": 1700678460970,
        "value": 217
      },
      {
        "code": "lower_temp",
        "custom_name": "",
        "dp_id": 26,
        "time": 1700073411557,
        "value": 180
      },
      {
        "code": "temp_correction",
        "custom_name": "",
        "dp_id": 27,
        "time": 1700073410634,
        "value": -15
      },
      {
        "code": "holiday_temp_set",
        "custom_name": "",
        "dp_id": 32,
        "time": 1699884863559,
        "value": 50
      },
      {
        "code": "holiday_days_set",
        "custom_name": "",
        "dp_id": 33,
        "time": 1700676000870,
        "value": 6
      },
      {
        "code": "week_program2",
        "custom_name": "",
        "dp_id": 37,
        "time": 1700072778610,
        "value": "AQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAABAAC0BgAAyAgAANIMAADSDgAA0hEAANIWAADIAAAAAAEAALQGAADICAAA0gwAANIOAADSEQAA0hYAAMgAAAAAAQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAABAAC0BgAAyAgAANIMAADSDgAA0hEAANIWAADIAAAAAAEAALQGAADICAAA0gwAANIOAADSEQAA0hYAAMgAAAAAAQAAtAYAAMgIAADSDAAA0g4AANIRAADSFgAAyAAAAAA="
      },
      {
        "code": "factory_reset",
        "custom_name": "",
        "dp_id": 39,
        "time": 1700073411532,
        "value": true
      },
      {
        "code": "child_lock",
        "custom_name": "",
        "dp_id": 40,
        "time": 1700073411546,
        "value": false
      },
      {
        "code": "countdown_left",
        "custom_name": "",
        "dp_id": 42,
        "time": 1699884863559,
        "value": 0
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 45,
        "time": 1699884878343,
        "value": 0
      },
      {
        "code": "temporary_time",
        "custom_name": "",
        "dp_id": 101,
        "time": 1700612233350,
        "value": 60
      },
      {
        "code": "total_time",
        "custom_name": "",
        "dp_id": 102,
        "time": 1700612460272,
        "value": 2
      },
      {
        "code": "temp_antifreezing",
        "custom_name": "",
        "dp_id": 103,
        "time": 1700677460007,
        "value": 140
      },
      {
        "code": "swing",
        "custom_name": "",
        "dp_id": 104,
        "time": 1700073411552,
        "value": 3
      },
      {
        "code": "time_period",
        "custom_name": "",
        "dp_id": 105,
        "time": 1699884863559,
        "value": 1
      },
      {
        "code": "electricity",
        "custom_name": "",
        "dp_id": 106,
        "time": 1699884863559,
        "value": 0
      },
      {
        "code": "curent_pro_time",
        "custom_name": "",
        "dp_id": 107,
        "time": 1700668801980,
        "value": "EQAWAAMGAwc="
      },
      {
        "code": "heatcool_heat_cool",
        "custom_name": "",
        "dp_id": 108,
        "time": 1700073411536,
        "value": "hc_heat"
      },
      {
        "code": "antifreezing_switch",
        "custom_name": "",
        "dp_id": 109,
        "time": 1700073411860,
        "value": true
      },
      {
        "code": "use_password",
        "custom_name": "",
        "dp_id": 110,
        "time": 1700073411864,
        "value": false
      },
      {
        "code": "true_off",
        "custom_name": "",
        "dp_id": 111,
        "time": 1700678542850,
        "value": false
      },
      {
        "code": "password",
        "custom_name": "",
        "dp_id": 116,
        "time": 1700073411948,
        "value": 0
      },
      {
        "code": "partial_key_lock",
        "custom_name": "",
        "dp_id": 118,
        "time": 1700073411729,
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1700678807061,
  "tid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

-----------------------------------------

_Originally posted by @andrus2049 in https://github.com/tuya/tuya-smart-life/issues/32#issuecomment-1823340116_

**Comment by andrus2049** [comment]
This is the diagnostics downloaded from HA:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.3",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
    "smartlife": {
      "version": "0.1.0",
      "requirements": [
        "tuya-device-sharing-sdk==0.1.8"
      ]
    }
  },
  "integration_manifest": {
    "domain": "smartlife",
    "name": "smartlife",
    "codeowners": [
      "@smartlife"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/smartlife",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "version": "0.1.0",
    "requirements": [
      "tuya-device-sharing-sdk==0.1.8"
    ],
    "is_built_in": false
  },
  "data": {
    "endpoint": "https://apigw.tuyaeu.com",
    "terminal_id": "1700173731796ygU0iP",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "name": "NEVE PRO W",
    "category": "wk",
    "product_id": "9myqvomgygt9zgcs",
    "product_name": "NEVE PRO W",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2023-11-13T14:14:23+00:00",
    "create_time": "2023-11-13T14:14:23+00:00",
    "update_time": "2023-11-13T14:14:23+00:00",
    "function": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "auto",
            "holiday",
            "manual"
          ]
        }
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 5,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "upper_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "lower_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "temp_correction": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": -30,
          "max": 30,
          "scale": 1,
          "step": 5
        }
      },
      "holiday_temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "holiday_days_set": {
        "type": "Integer",
        "value": {
          "unit": "day",
          "min": 0,
          "max": 3000,
          "scale": 0,
          "step": 1
        }
      },
      "factory_reset": {
        "type": "Boolean",
        "value": {}
      },
      "child_lock": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status_range": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "auto",
            "holiday",
            "manual"
          ]
        }
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 5,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "upper_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "temp_current": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 0,
          "max": 400,
          "scale": 1,
          "step": 1
        }
      },
      "lower_temp": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "temp_correction": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": -30,
          "max": 30,
          "scale": 1,
          "step": 5
        }
      },
      "holiday_temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 50,
          "max": 350,
          "scale": 1,
          "step": 1
        }
      },
      "holiday_days_set": {
        "type": "Integer",
        "value": {
          "unit": "day",
          "min": 0,
          "max": 3000,
          "scale": 0,
          "step": 1
        }
      },
      "factory_reset": {
        "type": "Boolean",
        "value": {}
      },
      "child_lock": {
        "type": "Boolean",
        "value": {}
      },
      "countdown_left": {
        "type": "Integer",
        "value": {
          "unit": "min",
          "min": 0,
          "max": 2880,
          "scale": 0,
          "step": 1
        }
      },
      "fault": {
        "type": "Bitmap",
        "value": {
          "label": [
            "e1",
            "e2",
            "e3",
            "e4",
            "e5",
            "e6",
            "e7",
            "e8",
            "e9",
            "e10"
          ]
        }
      }
    },
    "status": {
      "switch": true,
      "mode": "manual",
      "temp_set": 214,
      "upper_temp": 240,
      "temp_current": 217,
      "lower_temp": 180,
      "temp_correction": -15,
      "holiday_temp_set": 50,
      "holiday_days_set": 6,
      "factory_reset": true,
      "child_lock": false,
      "countdown_left": 0,
      "fault": 0
    },
    "home_assistant": {
      "name": "NEVE PRO W",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.neve_pro_w_none",
            "state": "heat_cool",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat_cool",
                "heat_cool",
                "heat_cool"
              ],
              "min_temp": 0.5,
              "max_temp": 35.0,
              "target_temp_step": 0.1,
              "preset_modes": [
                "holiday"
              ],
              "current_temperature": 21.7,
              "temperature": 21.4,
              "preset_mode": null,
              "friendly_name": "NEVE PRO W None",
              "supported_features": 17
            },
            "last_changed": "2023-11-22T18:33:50.114794+00:00",
            "last_updated": "2023-11-22T18:34:03.089034+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true
  }
 }

**Comment by amerend** [comment]
Hello, same device, same issue.
Did someone find a sulution?

**Comment by andrus2049** [comment]
Unfortunately IMHO it won't be solved in the near future, because HA climate component implementation is currently very limited and lacks of some critical settings, like obsolete and incomplete HVAC modes and presets, antifreezing settings, etc...
Moreover the HA climate platform is aimed to create an entity to control house heating or cooling with HA automations, while my thermostat has its own extensive internal logic (like hour/day programming) and settings, and only need to be included in a HA dashboard mainly to show how it's currently working, and in case for manually changing some temporary settings (like the daily phase target temperature).

I however eventually sorted the situation almost perfectly with a lot of work.

First, I installed:
[hass-localtuya](https://github.com/xZetsubou/hass-localtuya)
(an improved fork of the original localtuya)

I checked the Tuya IoT platform for retrieving the device ID and key and all the available data (DPs).
Then I manually configured all the DPs of my thermostat (at least those I need to manage), to create HA switch, list, sensor and number entities.
This step is indeed very complicated....

Secondly, I installed the [hass-template-climate](https://github.com/jcwillox/hass-template-climate) custom integration:
https://github.com/jcwillox/hass-template-climate
With this integration I could create a virtual climate entity to be used with a HA thermostat card.

This integration is very powerful, and even if not completely offering all my thermostat functionalities (i.e. presets are not currently included separately), it does all the rest beautifully.
Of course this integrtaion can't add functionalities that are not yet included in the HA climate component, it only allows to manually map retrieved entities to the default HA climate settings.

The custom integration climate settings are very complicated to configure by templating, as this activity consists in assigning all the entities that I need and have previously retrieved by the localtuya integration to the corresponding HA climate settings (using templating).
This whole work is very hard to complete correctly, it took me about a week to get the desired results.
The result is very satisfying even if not perfect because it's still missing presets, and I have still to integrate some values like those needed to set the duration of the temporary manual mode.

Some notes:
In the HA climate component HVAC modes HEAT and COOL indicate the manual modes, so they had to be be mapped by templating to my thermostat presets modes (i.e. the manual preset, while temporary and holiday presets are not mappable to HA HVAC modes). 
I had to map presets to HVAC modes because the jcwillox's climate template integration currently doesn't support templating HA presets.

Inside the HA thermostat card my thermostat ON/OFF switch is not separately controllable with a switch (because it's not supported by the HA climate compnent) so I had to map it to the HVAC mode OFF (by templating).
In my thermostat settings I don't need the cooling mode, so this has been left out and not templated, but it would be easy to add.

In case you own the same thermostat, I unfortunately can't export all my localtuya settings as this functionality is not provided by the integration, but I can export the template climate configuration.

**Comment by andrus2049** [comment]
HA dashboard (the thermostat is located in a remote holiday home)

Entities not supported by the native lovelace thermostat card are included in a separate lovelace entities card.
Currently, for reference I kept my created HA entity names identical to the original thermostat property names shown in the Tuya IoT platform. Of course entity names can be chosen according to personal preferences.

<img width="498" alt="Th1" src="https://github.com/tuya/tuya-smart-life/assets/36678690/f09970d4-5cad-4984-82c2-c80a5254d71d">

<img width="287" alt="Th2" src="https://github.com/tuya/tuya-smart-life/assets/36678690/17ee0be6-e843-4272-889f-c0e275922516">

**Comment by andrus2049** [comment]
My climate_template configuration in configuration.yaml:

```
climate:
  - platform: climate_template
    name: NEVE PRO
    unique_id: write_here_your_chosen_unique_id

# define here only climate component HACMode enums that have to be used by the climate_template
    modes:
      - "auto"
      - "heat"
      - "off"
#      - "heat_cool"    # left out, not clear to me what to be used for as there is already an auto mode.
#      - "cool"         # left out
#      - "fan_only"     # left out
#      - "dry"          # left out

    min_temp: 5
    max_temp: 24
    temp_step: 0.1
    precision: 0.1

    # current temp.
    current_temperature_template: "{{ states('sensor.neve_pro_temp_current') }}"

    # current humidity from a separate thermometer device
    current_humidity_template: "{{ states('sensor.sensore_2_umidita') }}"

    target_temperature_template: "{{ states('number.neve_pro_temp_set') }}"

    # availability.
    availability_template: "{{ states('switch.neve_pro') not in ['unknown', 'unavailable'] }}"

    set_temperature:
      - choose:
          - conditions: 
              - condition: template
                value_template: "{{ hvac_mode == 'heat' }}"
            sequence:
              - service: number.set_value
                data:
                  value: "{{ temperature }}"
                target:
                  entity_id: number.neve_pro_temp_set

# map only to climate component HACMode enums  !! (see defined modes above)
    hvac_mode_template: >-
        {% if states('switch.neve_pro') == 'on' and states('select.neve_pro_mode') == 'Auto' %}
          {{ 'auto' }}
        {% elif states('switch.neve_pro') == 'on' and states('select.neve_pro_mode') == 'Manual' %}
          {{ 'heat' }}
        {% elif states('switch.neve_pro') == 'off' %}
          {{ 'off' }}
        {% endif %}

# map only to climate component HVACAction enums !!
    hvac_action_template: >-
        {% if states('sensor.neve_pro_work_state') == 'off' %}
          {{ 'idle' }}
        {% elif states('sensor.neve_pro_work_state') == 'heat' %} 
          {{ 'heating' }}
        {% elif states('sensor.neve_pro_work_state') == 'cool' %}
          {{ 'cooling' }}
        {% else %}
          {{ 'off' }}
        {% endif %}

    set_hvac_mode:
      - choose:
          - conditions: 
              - condition: template
                value_template: "{{ hvac_mode == 'off' }}"
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.neve_pro
          - conditions:
               - condition: template
                 value_template: "{{ hvac_mode == 'auto' }}"
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.neve_pro
          - conditions:
               - condition: template
                 value_template: "{{ hvac_mode == 'heat' }}"
            sequence:
              - service: select.select_option
                data:
                  option: Manual
                target:
                  entity_id: select.neve_pro_mode

```

**Comment by andrus2049** [comment]
I finally found the hass-localtuya configuration export method so following there is my thermostat template:

```
- switch:
    current: '1'
    entity_category: None
    friendly_name: switch
    icon: ''
    id: '1'
    is_passive_entity: false
    platform: switch
    restore_on_reconnect: false
- sensor:
    device_class: temperature
    entity_category: diagnostic
    friendly_name: temp_current
    icon: ''
    id: '24'
    platform: sensor
    scaling: 0.1
    unit_of_measurement: "\xB0C"
- sensor:
    device_class: temperature
    entity_category: diagnostic
    friendly_name: temp_correction
    icon: ''
    id: '27'
    platform: sensor
    scaling: 0.1
    unit_of_measurement: "\xB0C"
- select:
    entity_category: config
    friendly_name: heatcool_heat_cool
    icon: ''
    id: '108'
    is_passive_entity: false
    platform: select
    restore_on_reconnect: false
    select_options:
      cool: Cool
      hc_cool: Hc_cool
      hc_heat: Hc_heat
      heat: Heat
- number:
    device_class: temperature
    entity_category: config
    friendly_name: temp_antifreezing
    icon: ''
    id: '103'
    is_passive_entity: false
    max_value: 150.0
    min_value: 5.0
    platform: number
    restore_on_reconnect: false
    scaling: 0.1
    step_size: 1.0
    unit_of_measurement: '*C'
- switch:
    entity_category: config
    friendly_name: antifreezing_switch
    icon: ''
    id: '109'
    is_passive_entity: false
    platform: switch
    restore_on_reconnect: false
- sensor:
    device_class: temperature
    entity_category: diagnostic
    friendly_name: lower_temp
    icon: ''
    id: '26'
    platform: sensor
    scaling: 0.1
    unit_of_measurement: '*C'
- sensor:
    device_class: temperature
    entity_category: diagnostic
    friendly_name: upper_temp
    icon: ''
    id: '19'
    platform: sensor
    scaling: 0.1
    unit_of_measurement: "\xB0C"
- number:
    device_class: temperature
    dps_default_value: '210'
    entity_category: config
    friendly_name: temp_set
    icon: ''
    id: '16'
    is_passive_entity: false
    max_value: 350.0
    min_value: 50.0
    platform: number
    restore_on_reconnect: false
    scaling: 0.1
    step_size: 1.0
    unit_of_measurement: "\xB0C"
- sensor:
    entity_category: diagnostic
    friendly_name: work_state
    icon: ''
    id: '3'
    platform: sensor
- select:
    dps_default_value: Auto
    entity_category: config
    friendly_name: mode
    icon: ''
    id: '2'
    is_passive_entity: false
    platform: select
    restore_on_reconnect: false
    select_options:
      auto: Auto
      holiday: Holiday
      manual: Manual
      temporary: Temporary
- number:
    device_class: temperature
    entity_category: config
    friendly_name: swing
    icon: ''
    id: '104'
    is_passive_entity: false
    max_value: 20.0
    min_value: 2.0
    platform: number
    restore_on_reconnect: false
    scaling: 0.1
    step_size: 1.0
    unit_of_measurement: "\xB0C"
- number:
    device_class: duration
    entity_category: config
    friendly_name: temporary_time
    icon: ''
    id: '101'
    is_passive_entity: false
    max_value: 2880.0
    min_value: 0.0
    platform: number
    restore_on_reconnect: false
    step_size: 1.0
    unit_of_measurement: min

```
