### ISSUE TITLE
Home Assistant Cannot Set Brightness with Color

### ISSUE THREAD

**Issue by bzaks1424** [tuya/tuya-smart-life#62]
In attempting to turn on my light with Home Assistant I cannot seem to set color in conjunction with brightness

Device Info:
```
"category": "dj",
"product_id": "6cej2z4aazmtrvge",
"product_name": "Color Light",
```

```
service: light.turn_on
target:
  entity_id: light.mike_light_none
data:
  rgb_color:
    - 255
    - 0
    - 0
  # brightness_step_pct: 100
  brightness: 100
```

Will result in the light turning to the last form of "white" (daylight, candlelight, etc...) and 100% brightness.  I expected it to turn 100% brightness and Red in color. brightness_step_pct also does not work.

I also attempted to make this change via scenes within HA - that also failed.
